In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [2]:
n = np.arange(1, 21)
ans = 2 ** n / n
ans

array([  2.00000000e+00,   2.00000000e+00,   2.66666667e+00,
         4.00000000e+00,   6.40000000e+00,   1.06666667e+01,
         1.82857143e+01,   3.20000000e+01,   5.68888889e+01,
         1.02400000e+02,   1.86181818e+02,   3.41333333e+02,
         6.30153846e+02,   1.17028571e+03,   2.18453333e+03,
         4.09600000e+03,   7.71011765e+03,   1.45635556e+04,
         2.75941053e+04,   5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [3]:
i = np.arange(0, 6)
s = 0.1 ** (3 * i) * 0.2 ** (4 * i)
ans = s.sum()
ans

1.00000160000256

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [4]:
A = np.zeros((8, 8))
A[::2, ::2] = 1
A[1::2, 1::2] = 1
A

array([[ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.]])

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [5]:
X = np.random.random((5, 2))

radius = np.sqrt(X[:, 0] ** 2 + X[:, 1] ** 2)
X[:, 1] = np.arccos(X[:, 0] / radius)
X[:, 0] = radius
X

array([[ 0.50023088,  0.87391093],
       [ 1.13859208,  0.89895377],
       [ 1.13842136,  0.78061116],
       [ 1.04570573,  0.74776626],
       [ 0.95380881,  1.36469631]])

**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [6]:
X = np.random.random((10, 10))

i = np.argmax(np.max(X, axis=1))
j = np.argmax(np.max(X, axis=0))
print(X[i, j])

0.973238327893


**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [7]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))

ans = X[np.argmin(np.sqrt(((X[:,0] - y[0,0]) ** 2 + (X[:,1] - y[0,1]) ** 2))), :]

**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [8]:
@np.vectorize
def func(x):
    if x < 0: 
        return x ** 2 + 2 * x + 6
    elif x < 2:
        return x + 6
    else: 
        return x ** 2 + 4 * x - 4

ans = func(np.arange(-3, 3.00001, 0.5))

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [9]:
X = np.random.random((10, 10))

X = (X.T - np.mean(X, axis=1)).T
np.mean(X, axis=1)

array([  4.44089210e-17,  -8.88178420e-17,  -7.77156117e-17,
        -3.33066907e-17,  -3.33066907e-17,   0.00000000e+00,
        -8.88178420e-17,   2.22044605e-17,   3.33066907e-17,
         1.11022302e-17])

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [10]:
X = np.random.normal(loc=5, scale=2., size=1000)
MX = np.mean(X)
DX = np.std(X) ** 2

**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [11]:
A = np.zeros((5,5))
A[0:5, :] = np.arange(5)
A[1,:] = np.roll(A[0,:], -1)
A[2,:] = np.roll(A[1,:], -1)
A[3,:] = np.roll(A[2,:], -1)
A[4,:] = np.roll(A[3,:], -1)